ALTER TABLE TB_SCREEN_MENU ADD COLUMN favorite_yn BOOLEAN DEFAULT 0 COMMENT '인기';
ALTER TABLE TB_SCREEN_MENU ADD COLUMN new_yn BOOLEAN DEFAULT 0 COMMENT '신규';
ALTER TABLE TB_SCREEN_MENU ADD COLUMN bond_yn BOOLEAN DEFAULT 0 COMMENT '채권운용';
ALTER TABLE TB_SCREEN_MENU ADD COLUMN stock_yn BOOLEAN DEFAULT 0 COMMENT '주식운용';
ALTER TABLE TB_SCREEN_MENU ADD COLUMN derivative_yn BOOLEAN DEFAULT 0 COMMENT '파생운용';

ALTER TABLE `tb_screen_menu` CHANGE COLUMN `derivative_yn` `derivative_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '파생운용' AFTER `stock_yn`;

ALTER TABLE TB_SCREEN_MENU ADD COLUMN check_link VARCHAR(128) COMMENT '체크화면링크';
